# _config.yml

theme: jekyll-theme-primer

# Very important: exclude backend and node_modules from build
exclude:
  - Backend/
  - node_modules/
  - vendor/
  - package-lock.json
  - package.json
  - yarn.lock
  - README.md
  - .gitignore
